server:
  port: 10100

spring:
  datasource:
    url: jdbc:mysql://47.106.103.111:3306/Netflix?serverTimezone=GMT%2B8&useSSL=FALSE
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  typeAliasesPackage: com.movie.**.domain
  mapperLocations: classpath*:mapper/**/*Mapper.xml